In [1]:
import pandas as pd

# Your original top-per-year data
top = pd.read_csv(r"C:\Users\Jiyoon\billboard-project\data\processed\top_per_year.csv")

# The new enriched dataset
enriched = pd.read_csv(r"C:\Users\Jiyoon\billboard-project\data\raw\Hot 100 Audio Features.csv")


print("Top per year shape:", top.shape)
print("Enriched shape:", enriched.shape)

Top per year shape: (64, 5)
Enriched shape: (29503, 23)

In [2]:
# clean top_per_year
top['song_clean'] = top['song'].str.lower().str.strip()
top['artist_clean'] = top['artist'].str.lower().str.strip()

#clean enriched dataset
enriched['song_clean'] = enriched['Song'].str.lower().str.strip()
enriched['artist_clean'] = enriched['Performer'].str.lower().str.strip()

print("Cleaning Done!")

Cleaning Done!

In [3]:
merged = top.merge(
    enriched[['song_clean', 'artist_clean', 'danceability', 'energy', 'valence', 'tempo', 'acousticness', 'speechiness',
              'instrumentalness', 'liveness', 'loudness']],
    on = ['song_clean', 'artist_clean'],
    how = 'left'
)

print("Merged shape: ", merged.shape)
print("Rows with audio features: ",merged['energy'].notna().sum())
print("Rows missing audio features:",merged['energy'].isna().sum())

Merged shape:  (65, 16)
Rows with audio features:  56
Rows missing audio features: 9

In [4]:
# matched songs
matched = merged[merged['energy'].notna()][['year', 'song', 'artist', 'tempo', 'energy', 'valence']]
print("MATCHED SONGS: ")
print(matched)

#didn't match
missing = merged[merged['energy'].isna()][['year','song', 'artist']]
print("\nMISSING SONGS: ")
print(missing)

MATCHED SONGS:
    year                                    song  \
0   1958                    It's All In The Game
1   1959                          Mack The Knife
2   1960         The Theme From "A Summer Place"
3   1961                     Tossin' And Turnin'
4   1962                 I Can't Stop Loving You
5   1963                             Sugar Shack
6   1964                I Want To Hold Your Hand
7   1965                               Yesterday
9   1967                          I'm A Believer
10  1968                                Hey Jude
12  1970              Bridge Over Troubled Water
13  1971                        Joy To The World
14  1972     The First Time Ever I Saw Your Face
15  1973         Killing Me Softly With His Song
16  1974                      Seasons In The Sun
18  1976  Tonight's The Night (Gonna Be Alright)
19  1977                    You Light Up My Life
20  1978                             Night Fever
21  1979                              My Sharona
22  1980                                 Call Me
23  1981                            Endless Love
24  1982                     I Love Rock 'N Roll
25  1983                   Every Breath You Take
26  1984                          When Doves Cry
28  1986             That's What Friends Are For
29  1987                      Livin' On A Prayer
30  1988                            Roll With It
31  1989                           Miss You Much
32  1990                    Nothing Compares 2 U
33  1991       (Everything I Do) I Do It For You
35  1993                  I Will Always Love You
36  1994                   I'll Make Love To You
37  1995                                 Fantasy
40  1998                         The Boy Is Mine
41  1999                                  Smooth
42  2000                             Maria Maria
43  2001                             All For You
44  2002                                 Foolish
45  2003                              In Da Club
46  2004                                   Yeah!
47  2005                      We Belong Together
48  2006                                SexyBack
49  2007                                Umbrella
50  2008                                     Low
51  2009                         I Gotta Feeling
53  2011                           We Found Love
54  2012                           Call Me Maybe
55  2013                           Blurred Lines
56  2014                                   Happy
57  2015                            Uptown Funk!
58  2016                                  Closer
59  2017                               Despacito
60  2018                              God's Plan
61  2019                           Old Town Road
62  2019                           Old Town Road
63  2020                                 The Box

                                               artist    tempo  energy  \
0                                       Tommy Edwards  105.181  0.2760
1                                         Bobby Darin   82.755  0.5290
2                       Percy Faith And His Orchestra   92.631  0.3890
3                                         Bobby Lewis  142.736  0.7220
4                                         Ray Charles   79.397  0.2790
5                      Jimmy Gilmer And The Fireballs  132.852  0.8040
6                                         The Beatles  130.726  0.7150
7                                         The Beatles   96.529  0.1790
9                                         The Monkees   80.106  0.7750
10                                        The Beatles  147.207  0.6070
12                                  Simon & Garfunkel   79.764  0.2060
13                                    Three Dog Night  126.990  0.6680
14                                      Roberta Flack  120.653  0.0264
15                                      Roberta Flack  121.568  0.3810
16                                        Terry Jacks   98.949  0.6110
18                                        Rod Stewart  136.542  0.5140
19                                        Debby Boone   77.986  0.3670
20                                           Bee Gees  103.564  0.8260
21                                          The Knack  147.245  0.7000
22                                            Blondie  142.673  0.8330
23                         Diana Ross & Lionel Richie   99.943  0.3400
24                        Joan Jett & the Blackhearts   94.379  0.7160
25                                         The Police  117.401  0.4520
26                                             Prince  126.470  0.9890
28                                   Dionne & Friends  120.117  0.2860
29                                           Bon Jovi  122.511  0.8870
30                                      Steve Winwood  117.254  0.6450
31                                      Janet Jackson  115.190  0.9750
32                                    Sinead O'Connor  119.917  0.5740
33                                        Bryan Adams  131.227  0.3720
35                                    Whitney Houston   66.980  0.2140
36                                        Boyz II Men  142.408  0.5090
37                                       Mariah Carey  102.358  0.7270
40                                    Brandy & Monica   93.145  0.7070
41                       Santana Featuring Rob Thomas  115.996  0.9230
42                  Santana Featuring The Product G&B   97.911  0.6010
43                                              Janet  113.511  0.8810
44                                            Ashanti   89.209  0.7280
45                                            50 Cent   90.096  0.7300
46                 Usher Featuring Lil Jon & Ludacris  105.018  0.7910
47                                       Mariah Carey  139.975  0.4690
48                                  Justin Timberlake  117.000  0.5830
49                            Rihanna Featuring Jay-Z  174.028  0.8290
50                          Flo Rida Featuring T-Pain  128.008  0.6090
51                                The Black Eyed Peas  127.965  0.7480
53                    Rihanna Featuring Calvin Harris  127.986  0.7660
54                                   Carly Rae Jepsen  120.069  0.5850
55             Robin Thicke Featuring T.I. + Pharrell  120.002  0.6080
56                                  Pharrell Williams  160.019  0.8220
57                   Mark Ronson Featuring Bruno Mars  114.988  0.6090
58                  The Chainsmokers Featuring Halsey   95.010  0.5240
59  Luis Fonsi & Daddy Yankee Featuring Justin Bieber  178.086  0.8160
60                                              Drake   77.169  0.4490
61                Lil Nas X Featuring Billy Ray Cyrus  136.041  0.6190
62                Lil Nas X Featuring Billy Ray Cyrus  136.041  0.6190
63                                        Roddy Ricch  116.971  0.5860

    valence
0    0.6540
1    0.4640
2    0.7490
3    0.9650
4    0.3770
5    0.8790
6    0.8660
7    0.3150
9    0.9620
10   0.5320
12   0.2640
13   0.9720
14   0.1390
15   0.3290
16   0.8210
18   0.7240
19   0.0685
20   0.9450
21   0.8970
22   0.7730
23   0.2300
24   0.9010
25   0.7400
26   0.8400
28   0.1990
29   0.7950
30   0.9540
31   0.6450
32   0.1610
33   0.2980
35   0.1080
36   0.2440
37   0.8010
40   0.7610
41   0.9610
42   0.6800
43   0.7750
44   0.6900
45   0.8080
46   0.5830
47   0.7780
48   0.9640
49   0.5750
50   0.3040
51   0.6000
53   0.6000
54   0.6260
55   0.8360
56   0.9620
57   0.9280
58   0.6610
59   0.8160
60   0.3570
61   0.6390
62   0.6390
63   0.6420

MISSING SONGS:
    year                                               song  \
8   1966                     The Ballad Of The Green Berets
11  1969  Aquarius/Let The Sunshine In (The Flesh Failures)
17  1975                         Love Will Keep Us Together
27  1985                                   We Are The World
34  1992                 End Of The Road (From "Boomerang")
38  1996                        Macarena (Bayside Boys Mix)
39  1997  Candle In The Wind 1997/Something About The Wa...
52  2010                                            TiK ToK
64  2021                                             Butter

                    artist
8        SSgt Barry Sadler
11       The 5th Dimension
17  The Captain & Tennille
27          USA For Africa
34             Boyz II Men
38             Los Del Rio
39              Elton John
52                   Ke$ha
64                     BTS

In [5]:
enriched_dedup = enriched.drop_duplicates(subset=['song_clean', 'artist_clean'], keep='first')
print("Before:", enriched.shape[0], "After:", enriched_dedup.shape[0])

Before: 29503 After: 29382

In [6]:
merged = top.merge(
    enriched_dedup[['song_clean', 'artist_clean', 'danceability', 'energy', 
               'valence', 'tempo', 'acousticness', 'speechiness',
               'instrumentalness', 'liveness', 'loudness']],
    on=['song_clean', 'artist_clean'],
    how='left'
)

print("Merged shape:", merged.shape)  # should now be (64, 16)

Merged shape: (64, 16)

In [7]:
# Search the enriched dataset for BTS songs
enriched[enriched['Performer'].str.contains('BTS', case=False, na=False)]

,index,SongID,Performer,Song,spotify_genre,spotify_track_id,spotify_track_preview_url,spotify_track_duration_ms,spotify_track_explicit,spotify_track_album,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,spotify_track_popularity,song_clean,artist_clean
2832,2832,Black SwanBTS,BTS,Black Swan,"['k-pop', 'k-pop boy group']",3bkkMZEAhx7rTVz1C0itRQ,https://p.scdn.co/mp3-preview/879c7106422b0b53...,198260.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0851,0.13700,0.000000,0.1290,0.490,147.023,4.0,72.0,black swan,bts
2921,2921,Blue & GreyBTS,BTS,Blue & Grey,"['k-pop', 'k-pop boy group']",0n2moJpAEWHwaPYYjkzMDl,https://p.scdn.co/mp3-preview/2a9059469af84164...,254950.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0415,0.42000,0.000000,0.1250,0.364,121.953,4.0,80.0,blue & grey,bts
3172,3172,Boy With LuvBTS Featuring Halsey,BTS Featuring Halsey,Boy With Luv,"['k-pop', 'k-pop boy group']",5KawlOMHjWeUjQtnuRs22c,https://p.scdn.co/mp3-preview/d16797fb391fb909...,229773.0,False,MAP OF THE SOUL : PERSONA,...,0.0965,0.09230,0.000000,0.1920,0.798,119.991,4.0,87.0,boy with luv,bts featuring halsey
5473,5473,Dis-easeBTS,BTS,Dis-ease,"['k-pop', 'k-pop boy group']",54DmTIv86D3sYdiawjULQ0,https://p.scdn.co/mp3-preview/0ceaed1d6b96fc04...,239722.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.1320,0.01320,0.000000,0.0782,0.484,101.085,4.0,78.0,dis-ease,bts
5511,5511,DNABTS,BTS,DNA,"['k-pop', 'k-pop boy group']",5SE57ljOIUJ1ybL9U6CuBH,https://p.scdn.co/mp3-preview/ef7f2f01d7b95b80...,223122.0,False,Love Yourself 承 'Her',...,0.0545,0.02200,0.000000,0.0677,0.687,129.819,4.0,73.0,dna,bts
6389,6389,DynamiteBTS,BTS,Dynamite,"['k-pop', 'k-pop boy group']",4saklk6nie3yiGePpBwUoc,https://p.scdn.co/mp3-preview/a707728846c105f4...,199053.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0993,0.01120,0.000000,0.0936,0.737,114.044,4.0,91.0,dynamite,bts
6959,6959,Fake LoveBTS,BTS,Fake Love,"['k-pop', 'k-pop boy group']",3aW0ds4A4tSQDIp75FqWTo,https://p.scdn.co/mp3-preview/bc24526c6a5e4d2a...,242333.0,False,Love Yourself 轉 'Tear',...,0.0372,0.00267,0.000000,0.3060,0.344,77.501,4.0,75.0,fake love,bts
7219,7219,Film OutBTS,BTS,Film Out,"['k-pop', 'k-pop boy group']",3UHPGOkUcE4hE7sqBF4Snt,NaN,214620.0,False,"{'album_type': 'single', 'artists': [{'externa...",...,0.1340,0.29600,0.000000,0.3310,0.314,164.032,4.0,86.0,film out,bts
7220,7220,FilterBTS,BTS,Filter,"['k-pop', 'k-pop boy group']",0ono6UCNVZ1XqOm6j78Blu,https://p.scdn.co/mp3-preview/43c93d00d5efbf03...,180220.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0626,0.02220,0.000000,0.1210,0.860,110.042,4.0,80.0,filter,bts
7403,7403,Fly To My RoomBTS,BTS,Fly To My Room,"['k-pop', 'k-pop boy group']",3QH8rQGNFX8VLbCgZ7uPTS,https://p.scdn.co/mp3-preview/178a7c05e3f026a2...,222242.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.2120,0.04840,0.000000,0.0718,0.588,114.910,4.0,79.0,fly to my room,bts
12244,12244,IDOLBTS Featuring Nicki Minaj,BTS Featuring Nicki Minaj,IDOL,"['k-pop', 'k-pop boy group']",2AIWoHr9DF6y4KALCBKWQS,https://p.scdn.co/mp3-preview/fc013a8d8851b4b8...,222732.0,False,Love Yourself 結 'Answer',...,0.1180,0.00481,0.000000,0.1230,0.422,126.035,4.0,77.0,idol,bts featuring nicki minaj
14555,14555,Life Goes OnBTS,BTS,Life Goes On,"['k-pop', 'k-pop boy group']",249gnXrbfmV8NG6jTEMSwD,https://p.scdn.co/mp3-preview/9dc29ff47cbdda2d...,207481.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0424,0.00691,0.000000,0.3700,0.450,81.068,4.0,87.0,life goes on,bts
14556,14556,Life Goes OnBTS,BTS,Life Goes On,"['k-pop', 'k-pop boy group']",249gnXrbfmV8NG6jTEMSwD,https://p.scdn.co/mp3-preview/9dc29ff47cbdda2d...,207481.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0424,0.00691,0.000000,0.3700,0.450,81.068,4.0,87.0,life goes on,bts
15898,15898,Make It RightBTS,BTS,Make It Right,"['k-pop', 'k-pop boy group']",314ZkcV7oLWG8yWE7LABvH,https://p.scdn.co/mp3-preview/fd5b0ad0cbe5fb2b...,226321.0,False,Make It Right (feat. Lauv),...,0.4250,0.03040,0.000000,0.1890,0.345,97.551,4.0,86.0,make it right,bts
15899,15899,Make It RightBTS Featuring Lauv,BTS Featuring Lauv,Make It Right,"['k-pop', 'k-pop boy group']",314ZkcV7oLWG8yWE7LABvH,https://p.scdn.co/mp3-preview/fd5b0ad0cbe5fb2b...,226321.0,False,Make It Right (feat. Lauv),...,0.4250,0.03040,0.000000,0.1890,0.345,97.551,4.0,84.0,make it right,bts featuring lauv
16320,16320,MIC DropBTS Featuring Desiigner,BTS Featuring Desiigner,MIC Drop,"['k-pop', 'k-pop boy group']",75scDPqGs75FotglJSoOI2,https://p.scdn.co/mp3-preview/b47d17ded8e53b76...,307675.0,False,Love Yourself 結 'Answer',...,0.1840,0.01140,0.000001,0.2060,0.540,170.010,4.0,75.0,mic drop,bts featuring desiigner
17167,17167,My TimeBTS,BTS,My Time,"['k-pop', 'k-pop boy group']",4vTgx6h4seHvkuFh84JXYP,https://p.scdn.co/mp3-preview/67513befcc0aea1b...,234457.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0339,0.15100,0.000000,0.0925,0.664,99.908,4.0,74.0,my time,bts
18151,18151,ONBTS,BTS,ON,"['k-pop', 'k-pop boy group']",249gnXrbfmV8NG6jTEMSwD,https://p.scdn.co/mp3-preview/9dc29ff47cbdda2d...,207481.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0424,0.00691,0.000000,0.3700,0.450,81.068,4.0,87.0,on,bts
18152,18152,ONBTS,BTS,ON,"['k-pop', 'k-pop boy group']",249gnXrbfmV8NG6jTEMSwD,https://p.scdn.co/mp3-preview/9dc29ff47cbdda2d...,207481.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0424,0.00691,0.000000,0.3700,0.450,81.068,4.0,87.0,on,bts
22669,22669,StayBTS,BTS,Stay,"['k-pop', 'k-pop boy group']",3ndCsZfq8OVwwkz9mmZvUz,https://p.scdn.co/mp3-preview/abcbd31b7da5f4ee...,204800.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0465,0.11400,0.000000,0.1300,0.341,125.904,4.0,78.0,stay,bts
23763,23763,TelepathyBTS,BTS,Telepathy,"['k-pop', 'k-pop boy group']",2FVpOsjT1iquZ3SpCjZ9Ne,https://p.scdn.co/mp3-preview/e057af6f770b0a7a...,202313.0,False,"{'album_type': 'album', 'artists': [{'external...",...,0.0428,0.00782,0.000000,0.1230,0.570,104.994,4.0,80.0,telepathy,bts
27007,27007,Waste It On MeSteve Aoki Featuring BTS,Steve Aoki Featuring BTS,Waste It On Me,"['big room', 'dance pop', 'edm', 'electro hous...",66XDf77gBcfQKi4I2vIbTj,https://p.scdn.co/mp3-preview/3f38a78b2bf15874...,192536.0,False,Neon Future III,...,0.0585,0.25200,0.000000,0.7200,0.466,96.097,4.0,73.0,waste it on me,steve aoki featuring bts

In [8]:
# Also try searching for "Butter" directly, in case the artist name is the issue
enriched[enriched['Song'].str.contains('Butter', case=False, na=False)]

,index,SongID,Performer,Song,spotify_genre,spotify_track_id,spotify_track_preview_url,spotify_track_duration_ms,spotify_track_explicit,spotify_track_album,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,spotify_track_popularity,song_clean,artist_clean
3205,3205,Bread And ButterRobert John,Robert John,Bread And Butter,['dublin indie'],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bread and butter,robert john
3206,3206,Bread And ButterThe Newbeats,The Newbeats,Bread And Butter,['northern soul'],4RJi2cYNOxfklHZZ7foR2y,https://p.scdn.co/mp3-preview/b9baeddfeb864832...,122720.0,False,The Newbeats,...,0.0469,0.757000,0.009810,0.1520,0.897,82.182,4.0,47.0,bread and butter,the newbeats
3404,3404,Build Me Up ButtercupThe Foundations,The Foundations,Build Me Up Buttercup,"['brill building pop', 'bubblegum pop', 'motown']",6sPOmDulFtLzfX25zICNrC,https://p.scdn.co/mp3-preview/a1286ea4146157ad...,177533.0,False,The Foundations,...,0.0294,0.313000,0.000000,0.2830,0.852,133.607,4.0,73.0,build me up buttercup,the foundations
3408,3408,Bullet With Butterfly WingsThe Smashing Pumpkins,The Smashing Pumpkins,Bullet With Butterfly Wings,"['alternative metal', 'alternative rock', 'gru...",6GtX0jaNL8IjVQfrDBx81z,NaN,258466.0,False,Mellon Collie And The Infinite Sadness (Deluxe...,...,0.0626,0.000056,0.836000,0.0466,0.475,121.649,4.0,73.0,bullet with butterfly wings,the smashing pumpkins
3481,3481,Butter BoyFanny,Fanny,Butter Boy,"['colombian pop', 'cumbia', 'ecuadorian pop', ...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,butter boy,fanny
3482,3482,ButterfliesMichael Jackson,Michael Jackson,Butterflies,"['pop', 'r&b', 'soul']",0rT9f5BSZrZ6DvzfBEckG0,https://p.scdn.co/mp3-preview/57baa67a5ea88b46...,279160.0,False,Invincible,...,0.0883,0.058300,0.000002,0.1100,0.545,89.990,4.0,58.0,butterflies,michael jackson
3483,3483,Butterfly BabyBobby Rydell,Bobby Rydell,Butterfly Baby,"['adult standards', 'brill building pop', 'bub...",2d1NLWc2wHDZWjKkgIjdls,NaN,134866.0,False,The Best Of Bobby Rydell,...,0.0335,0.169000,0.000000,0.6370,0.965,160.448,4.0,13.0,butterfly baby,bobby rydell
3484,3484,Butterfly DoorsLil Pump,Lil Pump,Butterfly Doors,"['emo rap', 'miami hip hop', 'rap', 'trap']",4NdXQlDTzxbOMkzJGWFtz3,https://p.scdn.co/mp3-preview/452b1a52556442ca...,132923.0,True,Butterfly Doors,...,0.1690,0.088900,0.000051,0.1440,0.429,130.008,4.0,66.0,butterfly doors,lil pump
3485,3485,Butterfly EffectTravis Scott,Travis Scott,Butterfly Effect,['rap'],2cYqizR4lgvp4Qu6IQ3qGN,https://p.scdn.co/mp3-preview/ca4f131887eae894...,190557.0,False,ASTROWORLD,...,0.0500,0.053100,0.000000,0.1140,0.193,140.958,4.0,85.0,butterfly effect,travis scott
3486,3486,Butterfly Fly AwayMiley Cyrus & Billy Ray Cyrus,Miley Cyrus & Billy Ray Cyrus,Butterfly Fly Away,"['dance pop', 'pop', 'post-teen pop']",2ZTCl6wQMDSMfY4s8GHZdj,NaN,189240.0,False,Hannah Montana The Movie,...,0.0258,0.733000,0.000123,0.2900,0.468,134.978,4.0,62.0,butterfly fly away,miley cyrus & billy ray cyrus
3487,3487,Butterfly KissesRaybon Bros.,Raybon Bros.,Butterfly Kisses,NaN,6dbQJo0gD0X8Pbpl9itIEj,NaN,284920.0,False,Raybon Bros.,...,0.0249,0.529000,0.000000,0.0858,0.127,85.791,4.0,8.0,butterfly kisses,raybon bros.
3488,3488,ButterflyCrazy Town,Crazy Town,Butterfly,"['alternative metal', 'funk metal', 'nu metal'...",4BggEwLhGfrbrl7JBhC8EC,https://p.scdn.co/mp3-preview/8bab4427d8ce0fcb...,216733.0,False,The Gift Of Game,...,0.0810,0.001320,0.000142,0.1070,0.609,103.502,4.0,71.0,butterfly,crazy town
3489,3489,ButterflyDanyel Gerard,Danyel Gerard,Butterfly,[],4bBAlCfQWO6f48QaHLHMtJ,https://p.scdn.co/mp3-preview/3b11b950d9989e60...,205014.0,False,Ein Hit des Jahrhunderts: Butterfly,...,0.0354,0.179000,0.000002,0.0851,0.493,82.483,4.0,21.0,butterfly,danyel gerard
5693,5693,Dog + ButterflyHeart,Heart,Dog + Butterfly,"['folk-pop', 'indie folk', 'indie pop', 'neo m...",00r40cNOJTjlNw5cG4ADHf,https://p.scdn.co/mp3-preview/2910e264953a471e...,319533.0,False,Dog & Butterfly,...,0.0329,0.314000,0.000005,0.1200,0.422,124.611,4.0,42.0,dog + butterfly,heart
6538,6538,Elusive ButterflyBob Lind,Bob Lind,Elusive Butterfly,['psychedelic folk rock'],226EXK5tPVsqaZ2y9RACR0,NaN,168533.0,False,Best Of,...,0.0262,0.099000,0.000000,0.0945,0.780,94.982,4.0,39.0,elusive butterfly,bob lind
7853,7853,Funny Little ButterfliesPatty Duke,Patty Duke,Funny Little Butterflies,['deep adult standards'],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,funny little butterflies,patty duke
18071,18071,Ole Buttermilk SkyBill Black's Combo,Bill Black's Combo,Ole Buttermilk Sky,[],7KINnXORWnM4NeNwrEqlTH,https://p.scdn.co/mp3-preview/365fcbf182044006...,131586.0,False,Bill Black's Greatest Hits,...,0.0439,0.762000,0.928000,0.3340,0.962,97.593,4.0,2.0,ole buttermilk sky,bill black's combo
18835,18835,Peanut ButterThe Marathons,The Marathons,Peanut Butter,[],5yL4zWTjLh3zJMXpU8hM1b,https://p.scdn.co/mp3-preview/52d6c2d1e53a10f4...,121720.0,False,Talkin' Trash,...,0.0312,0.403000,0.000000,0.3110,0.915,118.760,4.0,13.0,peanut butter,the marathons
18836,18836,Peanut ButterTwennynine Featuring Lenny White,Twennynine Featuring Lenny White,Peanut Butter,[],1avLYHHR0AEDmZVbicpWpu,https://p.scdn.co/mp3-preview/7479dd425c22f3fd...,217453.0,False,Best Of Friends,...,0.0587,0.054000,0.002050,0.1310,0.962,119.456,4.0,29.0,peanut butter,twennynine featuring lenny white
19424,19424,Pucker Up ButtercupJr. Walker & The All Stars,Jr. Walker & The All Stars,Pucker Up Buttercup,"['outlaw country', 'redneck']",5TbHBh0nrOLkgYmIWk7Q0l,NaN,177080.0,False,The Definitive Collection,...,0.0409,0.037300,0.000071,0.1880,0.715,127.131,4.0,22.0,pucker up buttercup,jr. walker & the all stars
24289,24289,The Crow & The ButterflyShinedown,Shinedown,The Crow & The Butterfly,"['alternative metal', 'nu metal', 'post-grunge']",1LkMC92Zc21awBWSHWZeGp,https://p.scdn.co/mp3-preview/1148fa8dba9e230e...,253600.0,False,The Sound of Madness,...,0.0329,0.001300,0.000000,0.0944,0.238,149.002,3.0,55.0,the crow & the butterfly,shinedown
26199,26199,Truffle ButterNicki Minaj Featuring Drake & Li...,Nicki Minaj Featuring Drake & Lil Wayne,Truffle Butter,"['dance pop', 'hip pop', 'pop', 'pop rap', 'po...",3keUgTGEoZJt0QkzTB6kHg,NaN,219226.0,True,Truffle Butter,...,0.0479,0.052500,0.000031,0.1200,0.523,105.098,4.0,65.0,truffle butter,nicki minaj featuring drake & lil wayne
28307,28307,Wings Of A ButterflyHIM,HIM,Wings Of A Butterfly,"['adult standards', 'indie pop']",5OdIePuf9dXmsJmQ98jRMp,https://p.scdn.co/mp3-preview/679b4544ec16c60f...,211679.0,False,XX - Two Decades Of Love Metal,...,0.0443,0.015200,0.015300,0.8340,0.667,128.038,4.0,48.0,wings of a butterfly,him